---
- name: find details with write-permissions for group  
  shell: "find -L {{ item }} -perm /go+w -type -f" 
  with_flattened: 
    - '/usr/local/sbin'
    - '/usr/local/bin'
    - '/usr/sbin'
    - '/sbin'
    - '/bin'

