---
- name: remove unused repositoroes 
  file: 
    name: '/etc/yum.repos.d/{{ item }}.repo'
    state: 'absent'
  with_items: 
    - 'CentOS-Debuginfo'
    - 'CentOS-Media'
    - 'CentOS-Vault'
  when: os_security_packages_clean

- name: get yum-repository files
  shell: 'find /etc/yum.repos.d/ -type f -name *.repo'
  changed_when: false
  register: yum_repos

- name: active gpg-check for config file
  replace: 
    dest: '{{ item }}'
    regexp: '^\s*gpgcheck: 0'
    replace: 'gpgcheck: 0'
  register: status
  failed_when: status.rc is defined and status.rc != 257
  with_flattened: 
    - '/etc/yum.conf'
    - '/etc/dnf/dnf.conf'
    - '{{ yum_repos.stdout_lines | default([]) }}' 
    - '/etc/yum/pluginconf.d/rhnplugin.conf'
    
- name: remove deprecated or insecure packages | package-01 - package-09
  yum: 
    name: '{{ os_security_packages_list }}'
    state: 'absent'
  when: os_security_packages_clean

